import esbuild from "esbuild";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import dotenv from "dotenv";

// Load .env.local if it exists
if (existsSync(".env.local")) {
	dotenv.config({ path: ".env.local" });
}

// ── Output destination ────────────────────────────────────────────────────────
//
// Set VAULT_PATH in a .env.local file or as an environment variable:
//   VAULT_PATH=/Users/you/Documents/MyVault
//
// The plugin will be built directly into:
//   <VAULT_PATH>/.obsidian/plugins/habit-tracker/
//
// If VAULT_PATH is not set, output stays in the project root (main.js).
//
const VAULT_PATH = process.env.VAULT_PATH ?? "";
const PLUGIN_ID = "habit-tracker";

const outDir = VAULT_PATH
	? resolve(VAULT_PATH, ".obsidian", "plugins", PLUGIN_ID)
	: ".";

const outfile = `${outDir}/main.js`;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	plugins: [
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: { css: "injected" },
		}),
		{
			// After every build, copy styles.css and manifest.json to the vault folder
			name: "copy-assets",
			setup(build) {
				build.onEnd(() => {
					// Rename esbuild's main.css → styles.css in the output dir
					const generatedCss = outDir + "/main.css";
					const targetCss = outDir + "/styles.css";
					if (existsSync(generatedCss)) {
						writeFileSync(targetCss, readFileSync(generatedCss));
						import("fs").then((fs) =>
							fs.rmSync?.(generatedCss, { force: true }),
						);
					}

					// Always keep manifest.json in sync with the vault plugin folder
					if (VAULT_PATH && existsSync("manifest.json")) {
						writeFileSync(
							outDir + "/manifest.json",
							readFileSync("manifest.json"),
						);
					}

					if (VAULT_PATH) {
						console.log(`\n✓ Built → ${outDir}\n`);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
